# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd1c6b91e84368d6449337b22e6ef1dca3e83d64e0153ecb769d72253ba5bf6d49c0017ec556ba1542494ef49a6d77321b45dc1af0e2ad072ce556d291561747

test:
  secret_key_base: 1600b378857e3215b6d545e53b8976c25384dfedaab8fd3a0d72bb664aed9d983ef4e1b5f013d5fb95daa15769962df32f689812911902dc7f401ffacbff23c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
